// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:2a3de9d3-7558-435f-a4c9-c9bf2676dbc5",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_pNXbJuOZd",
    "aws_user_pools_web_client_id": "5efbtupv2h2k41hfr4fukkiar6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://2rlgnaejcfhirf4siighrugy5u.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
