// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:8adecfe1-3510-4841-9156-ae7f665d4d23",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_eUvVWJiWw",
    "aws_user_pools_web_client_id": "1fpbokd4bafp44msp1vua3rv76",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://w5igj75iwfawhbhcu33lsfy44u.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "reactnativeunicorn88300538f0f04b888c4671acbb6cc07c-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
